import type { Metadata } from "next";
import { Geist, Geist_Mono, Hammersmith_One, Oswald  } from "next/font/google";
import Header from '../components/Header'
import "./globals.css";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const hammersmithOne = Hammersmith_One({
  variable: "--font-hammersmith-one",
  subsets: ["latin"],
  weight: "400", // Hammersmith One is typically only 'Regular' weight
  display: "swap", // Recommended for better perceived performance
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${hammersmithOne.variable} ${oswald.variable} antialiased`}
      > 
        <Header/>

        {children}
      </body>
    </html>
  );
}
